# Generated by Django 2.2.2 on 2020-05-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('date_close', models.DateTimeField()),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSE', 'Cerrada')], max_length=5)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('candidate_ids', models.ManyToManyField(to='users.Candidate')),
            ],
        ),
    ]
