# Generated by Django 2.2.2 on 2020-05-01 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_candidate_state'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='candidate_ids',
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('CANDIDATE', 'Aspirante'), ('SELECT', 'Seleccionado'), ('PROCESS', 'Proceso'), ('REJECTED', 'Rechazado')], max_length=12)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Candidate')),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.Offer')),
            ],
        ),
    ]
