# Generated by Django 2.2.2 on 2020-05-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20200501_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['date_create'], 'verbose_name_plural': 'Process'},
        ),
    ]
